# Generated by Django 3.1.2 on 2021-08-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210819_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='method',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
