# Generated by Django 3.1.2 on 2021-08-19 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_orderitem_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATM',
            fields=[
                ('baseentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.baseentity')),
                ('title', models.CharField(max_length=180)),
                ('price', models.IntegerField(default=0)),
                ('addon', models.IntegerField(default=0)),
                ('total_price', models.IntegerField(default=0)),
            ],
            bases=('base.baseentity',),
        ),
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(null=True, to='base.Inventory'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
