# Generated by Django 3.1.2 on 2021-08-19 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20210819_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='atm',
            name='other_info',
            field=models.TextField(null=True),
        ),
    ]
