# Generated by Django 3.1.2 on 2021-08-19 21:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_orderitem_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='atm',
            name='date',
            field=models.DateField(default=datetime.date(2021, 8, 19), null=True),
        ),
    ]
