# Generated by Django 3.1.2 on 2021-08-22 13:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20210822_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atm',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 8, 22, 13, 6, 46, 377903, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 8, 22, 13, 6, 46, 389932, tzinfo=utc), null=True),
        ),
    ]
