# Generated by Django 3.1.2 on 2021-08-22 15:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20210822_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='method',
            field=models.CharField(blank=True, default='cash', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='atm',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 8, 22, 15, 40, 47, 895874, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 8, 22, 15, 40, 47, 927123, tzinfo=utc), null=True),
        ),
    ]
