# Generated by Django 3.1.2 on 2021-08-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20210822_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atm',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
