# Generated by Django 3.1.2 on 2021-08-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20210822_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='method',
            field=models.CharField(blank=True, default='cash', max_length=250),
        ),
    ]
